#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const [fullCommand, name] = args;

const [namespace, action, type] = fullCommand.split(':');

if (namespace !== 'expressway' || action !== 'make') {
  console.log('❌ Unknown command. Try: expressway:make:<type>');
  process.exit(1);
}

const toPascal = str => str.charAt(0).toUpperCase() + str.slice(1);
const toKebab = str => str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
const Name = toPascal(name);
const kebabName = toKebab(name);

function writeFile(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
}

switch (type) {
  case 'controller':
    writeFile(`app/controllers/${name}Controller.js`, 
`const Controller = require('../../expressway/core/controller');

class ${Name}Controller extends Controller {
  index(req, res) {
    this.render(res, '${kebabName}', { message: 'Hello from ${Name}Controller!' });
  }
}

module.exports = new ${Name}Controller();`);
    console.log(`✅ Controller '${name}' created.`);
    break;

  case 'model':
    writeFile(`app/models/${name}Model.js`, 
`const { Model, DataTypes } = require('../../expressway/core/model');

class ${Name}Model extends Model {}

${Name}Model.initModel({
  // Define attributes here
});

module.exports = ${Name}Model;`);
    console.log(`✅ Model '${name}' created.`);
    break;

  case 'view':
    writeFile(`app/views/${kebabName}.ejs`,
`<h1>${Name} View</h1>
<p>Generated by expressway CLI.</p>`);
    console.log(`✅ View '${name}' created.`);
    break;

  case 'migration':
    const timestamp = Date.now();
    writeFile(`expressway/database/migrations/${timestamp}-${kebabName}.js`,
`module.exports = {
  up: async ({ DataTypes, sequelize }) => {
    await sequelize.getQueryInterface().createTable('${kebabName}s', {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      createdAt: DataTypes.DATE,
      updatedAt: DataTypes.DATE,
    });
  },

  down: async ({ sequelize }) => {
    await sequelize.getQueryInterface().dropTable('${kebabName}s');
  }
};`);
    console.log(`✅ Migration '${name}' created.`);
    break;

  default:
    console.log('❌ Unknown type. Use: controller | model | view | migration');
}
