version: '3.8'

services:
  expressway:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app         # Mount current dir to container
      - /usr/src/app/node_modules  # Avoid overwriting node_modules
    command: npm run dev
